### ISSUE TITLE
Levels descriptions

### ISSUE THREAD

**Issue by A-Beille** [fakemancat/geometry-dash-api#4]
The description of "Bloodbath" is "V2hvc2UgYmxvb2Qgd2lsbCBiZSBzcGlsdCBpbiB0aGUgQmxvb2RiYXRoPyBXaG8gd2lsbCB0aGUgdmljdG9ycyBiZT8gSG93IG1hbnkgd2lsbCBzdXJ2aXZlPyBHb29kIGx1Y2suLi4=". And that's it for every level.

**Comment by Unviray** [comment]
This is just encoded in base64

**Comment by A-Beille** [comment]
Thanks you a lot !
